Adding multiple image upload feature.

diff --git a/imgur b/imgur
--- a/imgur
+++ b/imgur
@@ -24,19 +24,36 @@ fi
 token=$(jq -r '.token' $FILE)
 
 # check arguments
+# if [ "$1" = "-h" -o "$1" = "--help" ] ; then
+# 	usage
+# 	exit 0
+# elif [ $# -ne 1 ]; then
+# 	if [ $# == 0 ]; then
+# 		kdialog --error "No file specified"
+# 	else
+# 		kdialog --error "Unexpected arguments"
+# 	fi
+# 	exit 16
+# elif [ ! -f "$1" ]; then
+# 	kdialog --error "File \"$1\" not found"
+# 	exit 1
+# elif [[ ${token} == "" ]]; then
+#   kdialog --error "Invali Token inside $FILE "
+#   exit 1
+# fi
+
+# Alternative Check multiple argument
+
 if [ "$1" = "-h" -o "$1" = "--help" ] ; then
 	usage
 	exit 0
-elif [ $# -ne 1 ]; then
-	if [ $# == 0 ]; then
-		kdialog --error "No file specified"
-	else
-		kdialog --error "Unexpected arguments"
-	fi
+
+elif [ $# == 0 ]; then
+	kdialog --error "No file specified"
 	exit 16
-elif [ ! -f "$1" ]; then
-	kdialog --error "File \"$1\" not found"
-	exit 1
+# elif [ ! -f "$1" ]; then
+# 	kdialog --error "File \"$1\" not found"
+# 	exit 1
 elif [[ ${token} == "" ]]; then
   kdialog --error "Invali Token inside $FILE "
   exit 1
@@ -64,24 +81,25 @@ kdialog --passivepopup "imgur: Uploading image ..." 3
 #response=$(curl -F "key=$apikey" -H "Expect: " -F "image=@$1" \
 #	http://imgur.com/api/upload.xml 2>/dev/null)
 
-response=$(curl -H "Authorization:Bearer $token" -F "image=@$1" https://api.imgur.com/3/upload 2>/dev/null)
-if [ $? -ne 0 ]; then
-	kdialog --error "Upload failed"
-	exit 2
-elif [ $(echo $response | grep -c "<error_msg>") -gt 0 ]; then
-	err1=$(echo $response | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/')
-	kdialog --error "$err1"
-	exit 3
-fi
+for img in "$@"
+do
+	response=$(curl -H "Authorization:Bearer $token" -F "image=@$img" https://api.imgur.com/3/upload 2>/dev/null)
+	if [ $? -ne 0 ]; then
+		kdialog --error "Upload failed"
+		exit 2
+	elif [ $(echo $response | grep -c "<error_msg>") -gt 0 ]; then
+		err1=$(echo $response | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/')
+		kdialog --error "$err1"
+		exit 3
+	fi
 
-# parse the response and output our stuff
-#url=$(echo $response | sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/')
-url=$(echo $response | jq -r '.data.link')
-#deleteurl=$(echo $response | sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/')
-#deletehash=$(echo $response | jq -r '.data.deletehash')
-#deleteurl=$(echo "https://api.imgur.com/3/image/$deletehash")
-
-
-qdbus org.kde.klipper /klipper org.kde.klipper.klipper.setClipboardContents "$url"
-
-kdialog --passivepopup "Done. Image link copied to the clipboard" 5
+	# parse the response and output our stuff
+	#url=$(echo $response | sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/')
+	url=$(echo $response | jq -r '.data.link')
+	#deleteurl=$(echo $response | sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/')
+	#deletehash=$(echo $response | jq -r '.data.deletehash')
+	#deleteurl=$(echo "https://api.imgur.com/3/image/$deletehash")
+	qdbus org.kde.klipper /klipper org.kde.klipper.klipper.setClipboardContents "$url"
+	wait
+done
+kdialog --passivepopup "Done. $@ Image link copied to the clipboard" 5
